grpc:
  port: 6562

server:
  port: 8481
management:
  server:
    port: 8482
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info

meeting:
  google:
    application-name: Meeting
    auth:
      token-directory: tokens
    calendar:
      application-id: 1
    directory:
      cache-ttl: 10m
