grpc:
  port: 6561

server:
  port: 8481
management:
  server:
    port: 8481
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: info

meeting:
  connector-endpoints:
    1:
      host: localhost
      port: 6562