server:
  port: 8080
management:
  server:
    port: 8486
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info

spring:
  thymeleaf:
    cache: false

meeting:
  user-recommendation:
    limit: 5
  application-endpoints:
    meeting-scheduler:
      host: localhost
      port: 6563
    identity:
      host: localhost
      port: 6561