server:
  port: 8080
management:
  server:
    port: 8486
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: debug

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "974211070499-360t350151qkbd38r7pa5r62ikq3ffrs.apps.googleusercontent.com"
            client-secret: "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"
            redirect-uri: "{baseUrl}/userHome"

meeting:
  user-recommendation:
    limit: 5
  application-endpoints:
    meeting-scheduler:
      host: localhost
      port: 6563
    identity:
      host: localhost
      port: 6561